language: python
dist: bionic
python: 3.6
env:
  global:
    - DEFAULT_INTERFACE=eth0 # needed to setup django context
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
services:
  - postgresql
install:
  - cd hubmap
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mv hubmap/test_settings.py hubmap/local_settings.py
  - cd -
  - cd hubmap/frontend
  - npm ci
  - cd -
script:
  - ./test.sh
