language: python
python: 3.7
env:
  - DEFAULT_INTERFACE=eth0 # needed to setup django context
install:
  - cd hubmap
  - pip install -r requirements.txt
  - cd -
    
  - cd hubmap/frontend
  - npm install
  - cd -
script:
  - ./test.sh
