language: python
dist: bionic
python: 3.6
env:
  - DEFAULT_INTERFACE=eth0 # needed to setup django context
install:
  - cd hubmap
  - pip install -r requirements.txt
  - cd -
  - cd hubmap/frontend
  - npm ci
  - cd -
script:
  - ./test.sh
