language: python
dist: bionic
python: 3.6
env:
  global:
    - DEFAULT_INTERFACE=eth0 # needed to setup django context
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - libgconf-2-4 # For Cypress
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # We also need to cache folder with Cypress binary
    - ~/.cache
services:
  - postgresql
install:
  - cd hubmap
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - mv hubmap/test_settings.py hubmap/local_settings.py
  - cd -
  - cd hubmap/frontend
  - npm ci
  - cd -
script:
  - ./test.sh
