# Generated by Django 2.2 on 2019-05-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study Parent class'},
        ),
    ]
