# Generated by Django 2.2 on 2019-06-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_auto_20190526_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueExpressionHeatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidney_color', models.CharField(max_length=7)),
                ('lung_color', models.CharField(max_length=7)),
                ('heart_color', models.CharField(max_length=7)),
                ('pancreas_color', models.CharField(max_length=7)),
                ('abdomencolor', models.CharField(max_length=7)),
                ('liver_color', models.CharField(max_length=7)),
                ('smallIntestine_color', models.CharField(max_length=7)),
                ('bladder_color', models.CharField(max_length=7)),
                ('largeIntestine_color', models.CharField(max_length=7)),
                ('spleen_color', models.CharField(max_length=7)),
                ('genes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.Gene')),
            ],
        ),
    ]
