# Generated by Django 2.2.2 on 2019-06-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0003_tissueexpressionheatmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissueexpressionheatmap',
            old_name='abdomencolor',
            new_name='abdomen_color',
        ),
        migrations.RemoveField(
            model_name='tissueexpressionheatmap',
            name='genes',
        ),
        migrations.AddField(
            model_name='gene',
            name='tissue_expression_heatmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.TissueExpressionHeatmap'),
        ),
    ]
