version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  uwsgi:
    build: uwsgi+python-env
    volumes:
      - ..:/opt/dataportal
    ports:
      - "5000:5000"
  nginx:
    build: nginx
    ports:
      - "8000:80"
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
