version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  uwsgi:
    image: "mruffalo/hubmap-data-portal-python:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
  react_app:
    image: "mruffalo/hubmap-data-portal-reactjs:latest"
    ports:
      - "3000:3000"
    expose:
      - 3000
#  nginx:
#    build: nginx
#    ports:
#      - "8000:80"
#      - "80:80"
#      - "443:443"
#    expose:
#      - 80
#      - 443
