version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=hubmap_db
      - POSTGRES_USER=hubmap_login
      - POSTGRES_PASSWORD=SFz0C96otU0i6Cgy3BP3tE7n5SEgt2Dj
    ports:
      - "5432:5432"
  uwsgi:
    image: "hubmap/data-portal-python-prod:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - /opt/hubmap-data-portal-static:/opt/hubmap-data-portal/static
      - /opt/secret:/opt/secret
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
#  nginx:
#    build: nginx
#    ports:
#      - "8000:80"
#      - "80:80"
#      - "443:443"
#    expose:
#      - 80
#      - 443
