version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=hubmap_db
      - POSTGRES_USER=hubmap_login
      - POSTGRES_PASSWORD=SFz0C96otU0i6Cgy3BP3tE7n5SEgt2Dj
    ports:
      - "5432:5432"
  uwsgi:
    image: "hubmap/data-portal-python:latest"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - /opt/hubmap-data-portal-static:/opt/hubmap-data-portal/static
  react_app:
    image: "hubmap/data-portal-reactjs:latest"
    ports:
      - "3000:3000"
    expose:
      - 3000
#  nginx:
#    build: nginx
#    ports:
#      - "8000:80"
#      - "80:80"
#      - "443:443"
#    expose:
#      - 80
#      - 443
