# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hugo_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('ensembl_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MassCytometryStudy',
            fields=[
                ('study_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Study')),
                ('proteins', models.ManyToManyField(to='dataportal.Protein')),
            ],
            bases=('dataportal.study',),
        ),
        migrations.CreateModel(
            name='ScRnaSeqStudy',
            fields=[
                ('study_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Study')),
                ('read_count_total', models.PositiveIntegerField()),
                ('cell_count', models.PositiveIntegerField()),
            ],
            bases=('dataportal.study',),
        ),
        migrations.CreateModel(
            name='SpatialTranscriptomicStudy',
            fields=[
                ('study_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Study')),
                ('genes', models.ManyToManyField(to='dataportal.Gene')),
            ],
            bases=('dataportal.study',),
        ),
        migrations.AddField(
            model_name='study',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.DataType'),
        ),
        migrations.AddField(
            model_name='study',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.Institution'),
        ),
        migrations.AddField(
            model_name='study',
            name='tissue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataportal.Tissue'),
        ),
        migrations.CreateModel(
            name='ScRnaSeqStudyBarcoded',
            fields=[
                ('scrnaseqstudy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.ScRnaSeqStudy')),
                ('unique_barcode_count', models.PositiveIntegerField()),
            ],
            bases=('dataportal.scrnaseqstudy',),
        ),
        migrations.CreateModel(
            name='ScRnaSeqStudyCDNA',
            fields=[
                ('scrnaseqstudy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.ScRnaSeqStudy')),
                ('read_count_aligned', models.PositiveIntegerField()),
            ],
            bases=('dataportal.scrnaseqstudy',),
        ),
    ]
