# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masscytometrystudy',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='scrnaseqstudybarcoded',
            name='genes',
            field=models.ManyToManyField(to='dataportal.Gene'),
        ),
        migrations.AddField(
            model_name='study',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
