# Generated by Django 2.2 on 2019-04-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Polygon', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quadrilateral',
            fields=[
                ('sides', models.IntegerField(default=4)),
                ('polygon_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Polygon')),
            ],
            bases=('dataportal.polygon',),
        ),
        migrations.CreateModel(
            name='Traingle',
            fields=[
                ('base', models.FloatField()),
                ('height', models.FloatField()),
                ('polygon_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Polygon')),
            ],
            bases=('dataportal.polygon',),
        ),
        migrations.CreateModel(
            name='Parallelogram',
            fields=[
                ('base', models.FloatField()),
                ('height', models.FloatField()),
                ('quadrilateral_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Quadrilateral')),
            ],
            bases=('dataportal.quadrilateral',),
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('quadrilateral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataportal.Quadrilateral')),
                ('side', models.FloatField()),
            ],
            bases=('dataportal.quadrilateral',),
        ),
    ]
