# Generated by Django 2.1.7 on 2019-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masscytometrystudy',
            name='sample_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
