# Generated by Django 2.2 on 2019-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_parallelogram_polygon_quadrilateral_square_traingle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadrilateral',
            name='polygon_ptr',
        ),
        migrations.RemoveField(
            model_name='square',
            name='quadrilateral_ptr',
        ),
        migrations.RemoveField(
            model_name='traingle',
            name='polygon_ptr',
        ),
        migrations.DeleteModel(
            name='Parallelogram',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
        migrations.DeleteModel(
            name='Quadrilateral',
        ),
        migrations.DeleteModel(
            name='Square',
        ),
        migrations.DeleteModel(
            name='Traingle',
        ),
    ]
