# Generated by Django 2.1.7 on 2019-03-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_auto_20190306_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
