# Generated by Django 2.1.7 on 2019-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0004_auto_20190326_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='masscytometrystudy',
            options={'verbose_name': 'Mass Cytometry'},
        ),
        migrations.AlterModelOptions(
            name='microscopystudy',
            options={'verbose_name': 'Microscopy'},
        ),
        migrations.AlterModelOptions(
            name='scthsseqstudy',
            options={'verbose_name': 'scTHS-seq'},
        ),
    ]
