# Generated by Django 2.1.7 on 2019-03-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0005_auto_20190329_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='samples',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dataportal.Samples'),
            preserve_default=False,
        ),
    ]
