# Generated by Django 2.1.7 on 2019-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0006_study_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masscytometrystudy',
            name='sample_count',
        ),
        migrations.AddField(
            model_name='samples',
            name='sample_count',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
