env:
  browser: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-console: [2, { "allow": ["warn", "error"]}]  # Lower levels used for debugging should not be checked in.
  react/jsx-filename-extension: [0]  # JSX is ubiquitous; We don't need to make it explicit.
  react/sort-comp: [0]  # Non-alphabetical groupings can make more sense.
  react/jsx-one-expression-per-line: [0]  # Makes punctuation after tab awkward.
