env:
  browser: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  camelcase # TODO
  class-methods-use-this # TODO
  func-names # TODO
  global-require # TODO
  import/no-extraneous-dependencies # TODO
  import/no-mutable-exports # TODO
  import/no-named-as-default # TODO
  import/no-named-as-default-member # TODO
  import/no-unresolved # TODO
  import/prefer-default-export # TODO
  max-len # TODO
  no-console # TODO
  no-plusplus # TODO
  no-return-assign # TODO
  no-undef # TODO
  no-unused-expressions # TODO
  no-unused-vars # TODO
  no-use-before-define # TODO
  react/destructuring-assignment # TODO
  react/forbid-prop-types # TODO
  react/jsx-filename-extension # TODO
  react/jsx-props-no-spreading # TODO
  react/prefer-stateless-function # TODO
  react/prop-types # TODO
