env:
  browser: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  camelcase: 0 # TODO
  class-methods-use-this: 0 # TODO
  func-names: 0 # TODO
  global-require: 0 # TODO
  import/no-extraneous-dependencies: 0 # TODO
  import/no-mutable-exports: 0 # TODO
  import/no-named-as-default: 0 # TODO
  import/no-named-as-default-member: 0 # TODO
  import/no-unresolved: 0 # TODO
  import/prefer-default-export: 0 # TODO
  max-len: 0 # TODO
  no-console: 0 # TODO
  no-plusplus: 0 # TODO
  no-return-assign: 0 # TODO
  no-undef: 0 # TODO
  no-unused-expressions: 0 # TODO
  no-unused-vars: 0 # TODO
  no-use-before-define: 0 # TODO
  react/destructuring-assignment: 0 # TODO
  react/forbid-prop-types: 0 # TODO
  react/jsx-filename-extension: 0 # TODO
  react/jsx-props-no-spreading: 0 # TODO
  react/prefer-stateless-function: 0 # TODO
  react/prop-types: 0 # TODO
