env:
  browser: true
  es6: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  arrow-body-style: 0 # TODO
  arrow-parens: 0 # TODO
  arrow-spacing: 0 # TODO
  brace-style: 0 # TODO
  camelcase: 0 # TODO
  class-methods-use-this: 0 # TODO
  comma-dangle: 0 # TODO
  comma-spacing: 0 # TODO
  destructuring-assignment: 0 # TODO
  dot-notation: 0 # TODO
  eol-last: 0 # TODO
  forbid-prop-types: 0 # TODO
  func-names: 0 # TODO
  global-require: 0 # TODO
  indent: 0 # TODO
  jsx-closing-bracket-location: 0 # TODO
  jsx-closing-tag-location: 0 # TODO
  jsx-curly-brace-presence: 0 # TODO
  jsx-filename-extension: 0 # TODO
  jsx-first-prop-new-line: 0 # TODO
  jsx-fragments: 0 # TODO
  jsx-indent: 0 # TODO
  jsx-indent-props: 0 # TODO
  jsx-max-props-per-line: 0 # TODO
  jsx-one-expression-per-line: 0 # TODO
  jsx-props-no-spreading: 0 # TODO
  jsx-quotes: 0 # TODO
  jsx-tag-spacing: 0 # TODO
  jsx-wrap-multilines: 0 # TODO
  key-spacing: 0 # TODO
  lines-between-class-members: 0 # TODO
  max-len: 0 # TODO
  newline-after-import: 0 # TODO
  no-console: 0 # TODO
  no-else-return: 0 # TODO
  no-extra-semi: 0 # TODO
  no-extraneous-dependencies: 0 # TODO
  no-multi-spaces: 0 # TODO
  no-multiple-empty-lines: 0 # TODO
  no-mutable-exports: 0 # TODO
  no-named-as-default: 0 # TODO
  no-named-as-default-member: 0 # TODO
  no-plusplus: 0 # TODO
  no-return-assign: 0 # TODO
  no-tabs: 0 # TODO
  no-trailing-spaces: 0 # TODO
  no-undef: 0 # TODO
  no-unresolved: 0 # TODO
  no-unused-expressions: 0 # TODO
  no-unused-vars: 0 # TODO
  no-use-before-define: 0 # TODO
  no-var: 0 # TODO
  object-curly-newline: 0 # TODO
  object-curly-spacing: 0 # TODO
  object-property-newline: 0 # TODO
  object-shorthand: 0 # TODO
  order: 0 # TODO
  padded-blocks: 0 # TODO
  prefer-const: 0 # TODO
  prefer-default-export: 0 # TODO
  prefer-stateless-function: 0 # TODO
  prefer-template: 0 # TODO
  prop-types: 0 # TODO
  quotes: 0 # TODO
  self-closing-comp: 0 # TODO
  semi: 0 # TODO
  space-in-parens: 0 # TODO
  space-infix-ops: 0 # TODO
  spaced-comment: 0 # TODO
  vars-on-top: 0 # TODO
  import/newline-after-import: 0 # TODO
  import/no-extraneous-dependencies: 0 # TODO
  import/no-mutable-exports: 0 # TODO
  import/no-named-as-default: 0 # TODO
  import/no-named-as-default-member: 0 # TODO
  import/no-unresolved: 0 # TODO
  import/order: 0 # TODO
  import/prefer-default-export: 0 # TODO
  react/destructuring-assignment: 0 # TODO
  react/forbid-prop-types: 0 # TODO
  react/jsx-closing-bracket-location: 0 # TODO
  react/jsx-closing-tag-location: 0 # TODO
  react/jsx-curly-brace-presence: 0 # TODO
  react/jsx-filename-extension: 0 # TODO
  react/jsx-first-prop-new-line: 0 # TODO
  react/jsx-fragments: 0 # TODO
  react/jsx-indent: 0 # TODO
  react/jsx-indent-props: 0 # TODO
  react/jsx-max-props-per-line: 0 # TODO
  react/jsx-one-expression-per-line: 0 # TODO
  react/jsx-props-no-spreading: 0 # TODO
  react/jsx-tag-spacing: 0 # TODO
  react/jsx-wrap-multilines: 0 # TODO
  react/prefer-stateless-function: 0 # TODO
  react/prop-types: 0 # TODO
  react/self-closing-comp: 0 # TODO
